name: dozer_mobile
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  uni_links: ^0.5.1
  autocomplete_textfield: ^2.0.1
  bottom_sheet: ^3.1.2
  build_runner: ^2.1.5
  cached_network_image: ^3.2.3
  camera: ^0.10.5+2
  connectivity: ^3.0.6
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.4.3+1
  dropdown_search: ^5.0.6
  equatable: ^2.0.5
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_messaging: ^14.7.10
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_datetime_picker: ^1.5.1
  flutter_dotenv: ^5.1.0
  flutter_polyline_points: ^1.0.0
  flutter_screenutil: ^5.9.0
  flutter_speed_dial: ^7.0.0
  flutter_spinkit: ^5.2.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.9
  flutter_typeahead: ^5.0.2
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  get: ^4.6.6
  get_it: ^7.6.0
  get_storage: ^2.1.1
  go_router: ^14.2.0
  google_fonts: ^4.0.4
  google_sign_in: ^6.1.6
  http: null
  image_picker: ^0.8.9
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0 # Update intl version to match flutter_localizations

  mockito: ^5.0.0
  otp_pin_field: ^1.2.2
  page_indicator: ^0.4.1
  permission_handler: ^11.0.1
  popup_menu: ^2.0.0
  rect_getter: ^1.1.0
  shared_preferences: ^2.1.2
  shimmer: ^3.0.0
  signalr_core: ^1.1.1
  signature: ^5.4.1
  sizer: ^2.0.15
  unicons: ^2.1.1
  url_launcher: ^6.1.12
  open_file: ^3.3.2
  pdf: ^3.10.8
  zego_uikit_prebuilt_live_audio_room: ^3.6.7
  webview_flutter: ^4.8.0
  chapasdk: ^0.0.6
  carousel_slider: ^4.2.1
  flutter_signature_pad: ^3.0.1
  printing: ^5.12.0
  flutter_pdfview: ^1.3.2
  awesome_dialog: ^3.2.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
